@startuml
actor User
boundary RestUI #DodgerBlue
participant JWTAuthentication #DodgerBlue
participant UserController #MediumSeaGreen
participant UserService #Salmon
participant AccountRepository #MediumSeaGreen
database Database #Salmon

group User/Admin Login
User -> RestUI : POST ../api/easyparking/login/?username={username}&password={password}
RestUI -> UserController : login(username, password)

UserController -> UserService :login(username, password)

UserService -> AccountRepository : GetUserByUsernameAndRole
AccountRepository -> Database : connection and retrieve data
Database -> AccountRepository : User
AccountRepository -> UserService : User
UserService -> JWTAuthentication : User
JWTAuthentication -> UserService : JWT
UserService -> UserController : JWT
UserController -> RestUI : JWT
RestUI -> User : 200 OK - HTML Response (User)
end
@enduml